### PR TITLE
chore: upgrade IBC to v6

### PR DESCRIPTION
**Pull request by aljo242**
Updates:
- `ibc-go` to `v6`
- `sdk` to `v0.46.7`
- `cosmos-proto` to `v1.0.0-beta.1`
- `tendermint` to `v0.34.24`

Modified `monitoringp` and `monitoringc` modules because the signature for `SendPacket` has been changed.

Tests working for me, but this could use some further investigation/testing

### CODE REVIEW

**Comment by aljo242** [comment]
`ignite/modules` needs to be upgrade to `ibc-go/v6` first.  Then I can update the dependency.

**Review by lubtd — APPROVED** [review]
LGTM

**Comment by lubtd** [comment]
> Modified monitoringp and monitoringc modules because the signature for SendPacket has been changed.
Tests working for me, but this could use some further investigation/testing

There is just the sequence added as far as I can see and it is retrieve by the channel keeper.
I don't see modification that influence verification logic

**Comment by aljo242** [comment]
Ok - feel free to merge

**Pull request merged**
