### PR TITLE
chore(bump versions): TM to 0.34.8 and to SDK 0.41.3

### PR DESCRIPTION
**Pull request by faddat**
This simply changes the versions for Tendermint and the SDK declared in go.mod and resolves a "bad handshake" issue with the websocket.

PS:  Websocket on the prior version did at one time work, so it's possible that issues will crop up again.

### CODE REVIEW

**Review by ilgooz — COMMENTED** [review]
For the notice, we may need replace directives in `go.mod` as well:

https://github.com/tendermint/liquidity/blob/5e57df68fbd8302440c9edc1780236be933876ea/go.mod#L24-L28

**Comment by faddat** [comment]
thank you, I'll do that.  Maybe that's why the faucet isn't working.

**Comment by faddat** [comment]
@ilgooz that may have broken it ( the replaced directives)

Let me fiddle....

**Review by ilgooz — APPROVED** [review]
Perfect! 🍻

**Pull request merged**
