### PR TITLE
refactor(x): Improve quality of code generated from templates

### LINKED ISSUE #217: Improve quality of code generated from templates
Quality from code generated from templates can sometime be improved (the generator can take some shortcut for conveniency)

We must review and improve code quality at the end of the milestone

What can be improved:
- Proto indentation
- Proto consistent field number for messages
- Put the function arguments on a single line when few arguments
- Remove unnecessary type for argument `(foo string, bar string)` -> `(foo, bar string)`
- For each types: verify the `<Type>Key(...)` method in `types/key_<type>.go` and try to simplify it (it is generally more complex than needed because template are type agnostic)
- Remove unecessary type cast (`string(foo)` when foo is a string). This can be recurrent in `x/cli/` files
- Remove unnecessary blank line

### PR DESCRIPTION
**Pull request by Pantani**
closes #217

### What does this PR does?

Improve quality of code generated from templates

### CODE REVIEW

**Review by ilgooz — APPROVED** [review]

**Comment by lubtd** [comment]
Seems fine for now. I will still wait for `MsgSettleRequest` to be merged to have a overall view on the code with all features

**Review by lubtd — DISMISSED** [review]
LGTM 👍

I pushed some commits for few details, you can have a look at them.
I approved, I think we fixed the big part, we can still do commits later for further details

**Review by ilgooz — APPROVED** [review]

**Review by lubtd — APPROVED** [review]

**Comment by lubtd** [comment]
Maybe we can wait all the Milestone 1 PRs to be merged before doing a final review

**Comment by lubtd** [comment]
We merged it since it's better for https://github.com/tendermint/spn/issues/273 to anticipate conflicts

**Pull request merged**
