### PR TITLE
feat(CI): test coverage

### LINKED ISSUE #231: Add a code test coverage CI action
Tests are important for blockchains, so is code coverage

### PR DESCRIPTION
**Pull request by Pantani**
closes #231

### CODE REVIEW

**Comment by lubtd** [comment]
Thanks for already have looked into this👍

Also I personally think that we shouldn't set a particular threshold for the coverage or try a specific value.
To me it would be more like a support when we implement a new feature to have a good sight of the scope of our tests

**Comment by Pantani** [comment]
> Thanks for already have looked into this👍
> 
> Also I personally think that we shouldn't set a particular threshold for the coverage or try a specific value.
> To me it would be more like a support when we implement a new feature to have a good sight of the scope of our tests

sure, we can define or remove the thresholds, I added a codecov config file

https://github.com/tendermint/spn/blob/feat/code-coverage/.codecov.yml

**Review by lubtd — APPROVED** [review]
This is awesome, all the config seems legit to me👍

Do we need the report on `develop` first to be able to access the full report?
Is there a way we can access the precise lines that are covered?

**Review by ilgooz — APPROVED** [review]

**Comment by Pantani** [comment]
> This is awesome, all the config seems legit to me👍
> 
> Do we need the report on `develop` first to be able to access the full report?
> Is there a way we can access the precise lines that are covered?

I'm not sure, but I think so

https://docs.codecov.com/docs/error-reference

**Review by lubtd — APPROVED** [review]

**Pull request merged**
