### PR TITLE
feat(CI): GitHub workflow for CI tests

### PR DESCRIPTION
**Pull request by Pantani**
### What does this MR does?

Create GitHub workflow to run CI tests

### Changes

- Add unit test workflow;
- Add lint test workflow;
- Add PR semantic test workflow;

### CODE REVIEW

**Review by fadeev — DISMISSED** [review]
🙌

**Review by lubtd — APPROVED** [review]
LGTM

**Comment by lubtd** [comment]
Just one comment before merging, shouldn't the name field be different for the different workflow. They are all named `Test` here

**Comment by Pantani** [comment]
> Just one comment before merging, shouldn't the name field be different for the different workflow. They are all named `Test` here

nice catch!! changed

**Review by fadeev — APPROVED** [review]

**Review by lubtd — APPROVED** [review]

**Pull request merged**
