### PR TITLE
refactor(`campaign`): remove `MsgAddVestingOptions`

### LINKED ISSUE #818: Remove entirely `MsgAddVestingOptions`
The message `MsgAddVestingOptions` has already been disabled since special allocations is a more flexible solution for vesting accounts
I consider removing message related logic completely since there is no plan enabling the message back.
- Message
- MainnetVestingAccount type and keeper
- MainnetVestingAccount related query

We can keep
- `types/share_vesting_options`
as a base for implementing the idea of vesting vouchers

### PR DESCRIPTION
**Pull request by aljo242**
Closes #818

### CODE REVIEW

**Review by lubtd — COMMENTED** [review]
We can also remove the commented block in `x/campaign/handler.go`

And we can remove everything related to `MainnetVestingAccount`
`mainnet_vesting_account.proto`
`cli/query_mainnet_vesting_account.go`
`keeper/grpc_mainnet_vesting_account.go`
`keeper/mainnet_vesting_account.go`
`types/mainnet_vesting_account.go`

In the future, if we introduce vouchers for vesting options, this part would be refactored heavily. Therefore, I think it's more beneficial to remove this now

**Comment by lubtd** [comment]
Indeed, I didn't know we used mainnet vesting account in the CLI but we can remove every occurrence of it

**Comment by lubtd** [comment]
@aljo242 I created a PR for remove mainnet vesting account from `cli` https://github.com/ignite-hq/cli/pull/2549

However, in this PR there is still reference to mainnet vesting accounts in
`x/campaign/genesis_test.go`
`x/campaign/keeper/invariants_test.go`

**Comment by aljo242** [comment]
Code is all merged - just waiting on changes to be made in Ignite CLI

**Review by Pantani — DISMISSED** [review]

**Comment by lubtd** [comment]
@Pantani I'm waiting for https://github.com/ignite-hq/cli/pull/2566 being merged to complete https://github.com/ignite-hq/cli/pull/2549

Is there anything blocking for https://github.com/ignite-hq/cli/pull/2566?

**Comment by Pantani** [comment]
> @Pantani I'm waiting for [ignite-hq/cli#2566](https://github.com/ignite-hq/cli/pull/2566) being merged to complete [ignite-hq/cli#2549](https://github.com/ignite-hq/cli/pull/2549)
> 
> Is there anything blocking for [ignite-hq/cli#2566](https://github.com/ignite-hq/cli/pull/2566)?

yes, I found some issues, but now the cosmogen is not generating the `mint` module for the vuex, I'm trying to find the issue

**Comment by Pantani** [comment]
> @Pantani I'm waiting for [ignite-hq/cli#2566](https://github.com/ignite-hq/cli/pull/2566) being merged to complete [ignite-hq/cli#2549](https://github.com/ignite-hq/cli/pull/2549)
> 
> Is there anything blocking for [ignite-hq/cli#2566](https://github.com/ignite-hq/cli/pull/2566)?

merged

**Comment by lubtd** [comment]
@aljo242 just pushed a fix for invariant test that was still taking Vesting Options into consideration

**Review by lubtd — APPROVED** [review]

**Pull request merged**
