### PR TITLE
chore: update the cli version

### PR DESCRIPTION
**Pull request by Pantani**

### CODE REVIEW

**Comment by lubtd** [comment]
Thanks for the PR🙏
Based on https://github.com/tendermint/spn/pull/827, we will have to use a new version of `cli` in `develop` that removes dependency with vesting options

**Comment by lubtd** [comment]
Let's wait on https://github.com/ignite-hq/cli/pull/2549 being merged and then let's import latest `cli`

**Comment by aljo242** [comment]
Looks like https://github.com/ignite-hq/cli/pull/2549 was merged, so we can update the package to the latest version and merge.

**Comment by Pantani** [comment]
> Looks like [ignite-hq/cli#2549](https://github.com/ignite-hq/cli/pull/2549) was merged, so we can update the package to the latest version and merge.

maybe it's better to merge [this one](https://github.com/tendermint/spn/pull/872) first and update everything into the CLI to generate a new version and update this PR

**Comment by lubtd** [comment]
Seems there was an issue with the version on the CLI, let's keep it pending now

**Comment by lubtd** [comment]
Updated dependency for `cli` with org updated

**Pull request merged**
