### PR TITLE
feat(chat): Implement transactions and queries to interact with messages

### PR DESCRIPTION
**Pull request by ltacker**
Implement transaction handlers for:
```
MsgSendMessage - Send a message to channel
MsgVotePoll - Vote a value to a message's poll
```

Implement the following queries:
```
list-messages [channel-id] - List all the messages in a channel
search-messages [tag] [channel-id] - List all the messages in a channel containing a specific tag
```

### CODE REVIEW

**Comment by fadeev** [comment]
@ltacker Trying it out, very exciting! 🙂

I think we may be missing `CmdListChannels`:

https://github.com/tendermint/spn/blob/message-interaction/x/chat/client/cli/query.go#L28

**Comment by ltacker** [comment]
Yep: #24

**Review by fadeev — APPROVED** [review]
🔥

**Review by ilgooz — APPROVED** [review]
:clinking_glasses:

**Pull request merged**
